import { paginateElement, pageAtOffset } from './pagination.js';
const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal');
const VERSION=1, KEY='holmes-chronicles-save-v1';
const defaults={font:19,speed:0,auto:5,mode:'stage',theme:'paper',sound:false};
let pendingOffset=null;
let catalog,characters={},book=null,index=0,page=0,pages=[],view='home',loadId=0,typing=null,autoTimer=null,auto=false,returnFocus=null,readingObserver=null,scrollTimer=null;
let save=readSave(),settings=cleanSettings(save.settings),cache=new Map(),audioContext=null;
function cleanSettings(s={}){return {font:Number.isFinite(s.font)?Math.max(16,Math.min(27,s.font)):defaults.font,speed:[0,25,45,75].includes(s.speed)?s.speed:defaults.speed,auto:Number.isFinite(s.auto)?Math.max(3,Math.min(12,s.auto)):defaults.auto,mode:s.mode==='reading'?'reading':'stage',theme:s.theme==='night'?'night':'paper',sound:s.sound===true}}
function readSave(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');if(s?.version===VERSION&&s.progress&&typeof s.progress==='object'&&!Array.isArray(s.progress)&&Array.isArray(s.seen)){s.seen=s.seen.filter(id=>typeof id==='string');s.settings=s.settings&&typeof s.settings==='object'?s.settings:{};return s}}catch{}return {version:VERSION,progress:{},seen:[],settings:{}}}
function persist(){save.settings=settings;try{localStorage.setItem(KEY,JSON.stringify(save))}catch{toast('この環境では記録を保存できません。設定から記録を書き出せます。')}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
function applySettings(){document.documentElement.style.setProperty('--font',settings.font+'px');document.body.classList.toggle('theme-night',settings.theme==='night')}
function halt(){clearInterval(typing);typing=null;clearTimeout(autoTimer);readingObserver?.disconnect();clearTimeout(scrollTimer)}
function icon(s){return `<span aria-hidden="true">${s}</span>`}
function characterPath(id){return characters[id]?.image||null}
function background(id){return catalog.backgrounds[id]||catalog.backgrounds['221b']}
function title(code){return catalog.works.find(w=>w.code===code)?.title||code}
function progress(code){return save.progress[code]||{index:0,page:0,maxIndex:0,complete:false}}
function cleanHistory(value,count){return Array.isArray(value)?value.filter(h=>h&&Number.isInteger(h.index)&&h.index>=0&&h.index<count&&Number.isInteger(h.end)&&h.end>0&&h.end<=1000000).slice(-60):[]}
function record(){if(!book)return;const old=progress(book.code),offset=pages.slice(0,page).join('').length,end=Math.min(book.blocks[index].text.length,offset+(pages[page]?.length||0)),history=cleanHistory(old.history,book.blocks.length),prior=history.find(h=>h.index===index);save.progress[book.code]={...old,index,page,offset,history:[...history.filter(h=>h.index!==index),{index,end:Math.max(prior?.end||0,end)}].slice(-60),maxIndex:Math.max(old.maxIndex||0,index),updated:Date.now()};save.last=book.code;persist()}
function rememberPeople(){for(const c of book.blocks[index]?.encounters||book.blocks[index]?.characters||[]){if(characters[c]&&characters[c].notebook!==false&&!save.seen.includes(c))save.seen.push(c)}persist()}
function ready(w){return !!w.ready}

async function boot(){try{[catalog,characters]=await Promise.all([fetch('data/catalog.json').then(checkResponse).then(r=>r.json()),fetch('data/characters.json').then(checkResponse).then(r=>r.json())]);await document.fonts.ready;applySettings();home();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});}catch(e){app.innerHTML=`<div class="boot"><p>事件簿を開けませんでした。</p><p class="small">通信を確認して、もう一度お試しください。</p><button class="primary" id="retry">再試行</button></div>`;$('#retry').onclick=boot}}
function checkResponse(r){if(!r.ok)throw Error('HTTP '+r.status);return r}
function home(){halt();auto=false;view='home';book=null;closeModal();const last=catalog.works.find(w=>w.code===save.last&&ready(w));const first=catalog.works.find(ready);app.innerHTML=`<section class="screen home"><div class="home-bg" style="background-image:url('${esc(background('221b'))}')"></div><img class="home-portrait" src="${esc(characterPath('holmes'))}" alt="ホームズ"><button class="home-menu" data-action="settings" aria-label="設定">⚙</button><header class="home-head"><p class="eyebrow">アーサー・コナン・ドイル</p><h1>ホームズ<span>全事件録</span></h1><div class="home-rule"></div><p class="home-sub">ワトソンの手記をひらく。<br>全60作品を、事件の順に。${catalog.edition?'<br>'+esc(catalog.edition.label)+' · 日本語全文60作品':catalog.releaseReady?'':'<br>制作中：'+catalog.works.filter(ready).length+'作品の全文を収録'}</p></header><nav class="home-actions"><button class="primary" data-action="start" ${first?'':'disabled'}>${last?'続きを読む':'最初の事件から'}<small>${esc(last?.title||first?.title||'本文を準備しています')}</small></button><button class="secondary" data-action="library">事件を選ぶ</button><button class="secondary" data-action="people">人物帳</button></nav><footer class="home-footer"><span>日本語全文 · 自動保存</span><button data-action="about">この事件簿について</button></footer></section>`;app.querySelector('[data-action=start]').onclick=()=>loadBook(last?.code||first?.code);wireActions(app)}
async function loadBook(code,target=null){if(!code)return;const meta=catalog.works.find(w=>w.code===code);if(!ready(meta)){toast('この作品の本文は準備中です。');return}halt();auto=false;closeModal();const request=++loadId;app.innerHTML='<p class="boot">手記を開いています…</p>';try{let value=cache.get(code);if(!value){value=await fetch(`data/stories/${code}.json`).then(checkResponse).then(r=>r.json());if(!Array.isArray(value.blocks)||!value.blocks.length)throw Error('Empty story');cache.set(code,value)}if(request!==loadId)return;book=value;index=Math.min(Math.max(0,target?.index??progress(code).index??0),book.blocks.length-1);page=Math.max(0,target?.page??progress(code).page??0);pendingOffset=target?.offset??(target?null:progress(code).offset??null);view='reader';if(settings.mode==='reading')renderReading();else renderStage();record()}catch(e){if(request!==loadId)return;view='home';app.innerHTML='<div class="boot"><p>この手記を読み込めませんでした。</p><p class="small">一度読んだ作品は、保存済みなら通信なしで開けます。</p><button class="primary" id="back-home">事件簿へ戻る</button></div>';$('#back-home').onclick=home}}
function readerHeader(){const meta=catalog.works.find(w=>w.code===book.code),pct=Math.floor(index/Math.max(1,book.blocks.length-1)*100);return `<header class="reader-head"><button class="icon-button" data-action="home" aria-label="事件簿へ戻る">${icon('⌂')}</button><div class="reader-heading"><h1>${esc(meta.title)}</h1><p>${esc(meta.dateLabel||'年代の手がかりをたどる')}</p></div><span class="progress-ring" aria-label="読書位置">${pct}%</span><button class="icon-button" data-action="library" aria-label="事件を選ぶ">${icon('☷')}</button></header>`}
function portraitFor(b){const cast=(b.stageCharacters||b.characters||[]).filter(c=>characterPath(c)&&characters[c].stageEligible!==false);let portrait=Object.hasOwn(b,'portrait')?(characterPath(b.portrait)?b.portrait:null):b.speaker!=='narration'?(characterPath(b.speaker)?b.speaker:null):(cast.includes('holmes')?'holmes':cast.includes('watson')?'watson':cast[0]||null);if(portrait&&b.actorVariants?.[portrait]){const variant=b.actorVariants[portrait];portrait=characterPath(variant)?variant:null}return portrait}
function renderStage(){halt();view='reader';const b=book.blocks[index];const speaker=b.speakerLabels?.[b.speaker]||b.speakerLabel||characters[b.speaker]?.name|| (b.speaker==='narration'?'ワトソンの手記':'手記');const narrator=b.narratorLabel||(book.narrator==='holmes'?'ホームズの手記':book.narrator==='third'?'記録':speaker);const portrait=portraitFor(b),framing=catalog.backgroundFraming?.[b.scene];
app.innerHTML=`<section class="reader ${settings.mode==='reading'?'text-only':''} ${(characters[portrait]?.stagePlacement==='ground'||framing?.mode==='stage')?'ground-scene':''}"><div class="scene-bg" style="background-image:url('${esc(background(b.scene))}')${framing?.mode==='stage'?';background-position:center '+framing.focusY+'%;background-size:'+framing.fit+';background-repeat:no-repeat;background-color:#172320':''}"></div><div class="scene-shade"></div>${readerHeader()}<div class="stage">${portrait?`<img class="character${characters[portrait]?.category==='animal'?' animal':''}${characters[portrait]?.stagePlacement==='ground'?' ground':''}" src="${esc(characterPath(portrait))}" alt="" style="--actor-scale:${characters[portrait]?.scale||1};--actor-lower:${Math.max(0,1-(characters[portrait]?.scale||1))};--ground-shift:${(1-(characters[portrait]?.groundBounds?.[3]??1))*100}%">`:''}${b.kind==='heading'?'<span class="stage-caption">手記をたどる</span>':''}</div><section class="dialogue-wrap"><p class="speaker">${esc(b.speaker==='narration'?narrator:speaker)}</p><div class="dialogue-panel" id="advance" tabindex="0" role="button" aria-label="本文。タップして次へ"><div class="dialogue ${b.kind==='heading'?'heading':''}" id="dialogue"></div><div class="dialogue-bottom"><span class="page-number"></span>${b.images?.length||b.notes?.length?'<button class="evidence-button" id="evidence">資料</button>':''}<span class="next-mark" aria-hidden="true"></span></div></div></section><nav class="toolbar"><button data-action="previous" aria-label="前の文章へ"><span class="symbol">‹</span>戻る</button><button data-action="history"><span class="symbol">☷</span>履歴</button><button data-action="auto" aria-pressed="${auto}"><span class="symbol">▷</span>自動</button><button data-action="${settings.mode==='reading'?'stage':'reading'}"><span class="symbol">文</span>${settings.mode==='reading'?'情景表示':'本文のみ'}</button><button data-action="settings"><span class="symbol">⚙</span>設定</button></nav></section>`;
pages=paginateElement(b.text,$('#dialogue'));page=pendingOffset!==null?pageAtOffset(pages,pendingOffset):page<0?pages.length-1:Math.min(page,pages.length-1);pendingOffset=null;$('.page-number').textContent=`${index+1} / ${book.blocks.length}${pages.length>1?' · '+(page+1)+'/'+pages.length:''}`;$('.next-mark').textContent=index===book.blocks.length-1&&page===pages.length-1?'読了へ':'つづきを読む ▾';wireActions(app);const advance=$('#advance');advance.onclick=e=>{if(e.target.closest('button')||getSelection()?.toString())return;next()};advance.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target===advance){e.preventDefault();next()}};if($('#evidence'))$('#evidence').onclick=e=>{e.stopPropagation();showEvidence(b)};showText(pages[page]);record();preloadNext();}
function showText(text){const el=$('#dialogue');if(!el)return;const letters=typeof Intl.Segmenter==='function'?Array.from(new Intl.Segmenter('ja',{granularity:'grapheme'}).segment(text),v=>v.segment):Array.from(text);if(!settings.speed||matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=text;scheduleAuto();return}let n=0;el.textContent='';typing=setInterval(()=>{n=Math.min(letters.length,n+2);el.textContent=letters.slice(0,n).join('');if(n===letters.length){clearInterval(typing);typing=null;scheduleAuto()}},2000/settings.speed)}
function next(){if(!book||!modal.hidden)return;if(typing){clearInterval(typing);typing=null;$('#dialogue').textContent=pages[page];scheduleAuto();return}clickSound();if(page+1<pages.length){page++;renderStage()}else if(index+1<book.blocks.length){rememberPeople();index++;page=0;pendingOffset=null;renderStage()}else finishBook()}
function previous(){if(!book)return;halt();if(page>0)page--;else if(index>0){index--;page=-1}renderStage()}
function scheduleAuto(){clearTimeout(autoTimer);if(auto&&modal.hidden&&view==='reader'&&(settings.mode==='stage'||settings.mode==='reading')&&!document.hidden)autoTimer=setTimeout(next,Math.max(settings.auto*1000,Array.from(pages[page]||'').length*75));}
function toggleAuto(){auto=!auto;const b=app.querySelector('[data-action=auto]');b?.setAttribute('aria-pressed',String(auto));scheduleAuto()}
const preloadedArt=new Set();
function preloadNext(){const nextBlock=book.blocks[index+1];if(!nextBlock)return;const actor=portraitFor(nextBlock);for(const src of [background(nextBlock.scene),actor&&characterPath(actor)]){if(src&&!preloadedArt.has(src)){preloadedArt.add(src);const im=new Image();im.src=src;im.onerror=()=>preloadedArt.delete(src)}}}
function renderReading(){settings.mode='reading';renderStage();persist()}
function repaginate(){if(!book||view!=='reader')return;pendingOffset=pages.slice(0,page).join('').length;renderStage()}
function finishBook(){halt();auto=false;rememberPeople();save.progress[book.code]={...progress(book.code),complete:true,index:book.blocks.length-1,page:0,maxIndex:book.blocks.length-1,updated:Date.now()};persist();const work=catalog.works.find(w=>w.code===book.code),pos=catalog.works.indexOf(work),nextWork=catalog.works.slice(pos+1).find(ready);openModal('手記を閉じる',`<div class="end-card"><p class="eyebrow">読了</p><h2>${esc(work.title)}</h2><p>この事件の手記を読み終えました。</p><div class="modal-actions">${nextWork?`<button class="primary" id="next-case">次の事件へ<small>${esc(nextWork.title)}</small></button>`:''}<button data-action="library">事件を選ぶ</button><button data-action="home">事件簿へ戻る</button></div></div>`);if($('#next-case'))$('#next-case').onclick=()=>loadBook(nextWork.code,{index:0,page:0})}
function openModal(name,body){clearTimeout(autoTimer);returnFocus=document.activeElement;modal.hidden=false;modal.innerHTML=`<section class="modal-card" role="dialog" aria-modal="true" aria-label="${esc(name)}"><header class="modal-top"><h2>${esc(name)}</h2><button class="close" aria-label="閉じる">×</button></header>${body}</section>`;$('.close').onclick=closeModal;wireActions(modal);$('.close').focus();modal.scrollTop=0}
function closeModal(){const wasOpen=!modal.hidden;modal.hidden=true;modal.innerHTML='';if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});if(wasOpen&&book&&view==='reader')repaginate();scheduleAuto()}
function showLibrary(order='chronology',query=''){let list=[...catalog.works];if(order==='publication')list.sort((a,b)=>a.publicationOrder-b.publicationOrder);openModal('事件を選ぶ',`<input class="search" id="search-cases" type="search" value="${esc(query)}" placeholder="作品名で探す" aria-label="作品名で探す"><nav class="tabs"><button id="chrono-order" class="${order==='chronology'?'active':''}">事件の推定順</button><button id="pub-order" class="${order==='publication'?'active':''}">英国発表順</button></nav><p class="small" style="margin-bottom:16px">年代に幅のある事件は、本文の手がかりから位置を推定しています。</p><div class="case-list" id="cases"></div>`);
const draw=q=>{$('#cases').innerHTML=list.filter(w=>(w.title+w.code+(w.alternateTitles||[]).join('')).toLowerCase().includes(q.toLowerCase())).map(w=>{const p=progress(w.code),pct=p.complete?100:Math.round((p.maxIndex||0)/Math.max(1,w.blockCount||1)*100);return `<button class="case-card" data-code="${esc(w.code)}"><span class="num">${String(catalog.works.indexOf(w)+1).padStart(2,'0')}</span><div><h3>${esc(w.title)}</h3><p>${esc(w.dateLabel||'年代を検討中')} · ${p.complete?'読了':pct?`${pct}%`:(w.type==='novel'?'長編':'短編')}${!ready(w)?' · 本文準備中':''}</p></div><span class="completion" style="width:${pct}%"></span></button>`}).join('')||'<p class="empty">該当する作品はありません。</p>';$('#cases').querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>showCase(b.dataset.code))};draw(query);$('#search-cases').oninput=e=>draw(e.target.value);$('#chrono-order').onclick=()=>showLibrary('chronology',$('#search-cases').value);$('#pub-order').onclick=()=>showLibrary('publication',$('#search-cases').value)}
function showCase(code){const w=catalog.works.find(v=>v.code===code),p=progress(code);openModal(w.title,`<p class="eyebrow">${esc(w.dateLabel||'年代を検討中')}</p><div class="case-detail"><p>${esc(w.chronologyNote||'時系列の位置を本文から検討しています。')}</p>${w.chronologyEvidence?.length?`<details><summary>年代の根拠を見る</summary>${w.chronologyEvidence.map(x=>`<p>${esc(x.note)}${x.url?` <a href="${esc(x.url)}" target="_blank" rel="noopener">原文</a>`:''}</p>`).join('')}</details>`:''}</div>${w.chapters?.length?`<details class="chapter-menu"><summary>章から読む</summary><div class="chapter-list">${w.chapters.map(c=>`<button data-chapter="${c.index}">${c.part?`<small>${esc(c.part)}</small>`:''}<span>${esc(c.label)}</span></button>`).join('')}</div></details>`:''}<p class="small">${catalog.edition?esc(catalog.edition.label)+' · 場面演出 '+catalog.edition.fullyStagedWorks+'/60作品<br>':''}${w.type==='novel'?'長編':'短編'} · ${esc(w.collection||'')}<br>${p.complete?'この作品は読了済みです。':'進み具合は、この端末に保存されます。'}</p><div class="modal-actions"><button class="primary" id="case-resume" ${ready(w)?'':'disabled'}>${p.index?'続きから読む':'読む'}</button>${p.index?'<button id="case-restart">はじめから読む</button>':''}<button data-action="library">事件一覧へ</button></div>`);$('#case-resume').onclick=()=>loadBook(code);modal.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>loadBook(code,{index:Number(b.dataset.chapter),page:0,offset:0}));if($('#case-restart'))$('#case-restart').onclick=()=>loadBook(code,{index:0,page:0})}
function showHistory(){if(!book)return;const currentEnd=pages.slice(0,page+1).join('').length,rows=cleanHistory(progress(book.code).history,book.blocks.length).filter(h=>h.index<=index).sort((a,b)=>a.index-b.index);openModal('読んだ文章',`<p class="small">表示した文章の履歴です。押すと、その段落の先頭に戻ります。</p>${rows.map(h=>{const b=book.blocks[h.index],end=h.index===index?Math.min(h.end,currentEnd):h.end;return `<button class="history-item" data-jump="${h.index}"><small>${esc(b.speakerLabels?.[b.speaker]||b.speakerLabel||characters[b.speaker]?.name||'手記')}</small><span>${esc(b.text.slice(0,end))}</span></button>`}).join('')}`);modal.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{index=Number(b.dataset.jump);page=0;pendingOffset=0;closeModal();settings.mode==='reading'?renderReading():renderStage()});modal.scrollTop=modal.scrollHeight}
function showPeople(){const ids=save.seen.filter(id=>characters[id]?.image&&characters[id].notebook!==false);openModal('人物帳',`<p class="small" style="margin-bottom:18px">文章を読み終えると、そこに名前が出てきた人物が加わります。</p>${ids.length?`<div class="people-grid">${ids.map(id=>`<button class="person-card" data-person="${esc(id)}"><img src="${esc(characterPath(id))}" alt="" loading="lazy"><span>${esc(characters[id].name)}</span></button>`).join('')}</div>`:'<p class="empty">まだ人物の記録がありません。最初の手記をひらいてみましょう。</p>'}`);modal.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const c=characters[b.dataset.person];openModal(c.name,`<div style="background:#52605222"><img src="${esc(c.image)}" style="max-height:68vh;margin:auto;object-fit:contain" alt="${esc(c.name)}"></div><div class="modal-actions"><button data-action="people">人物帳へ</button></div>`)})}
function showEvidence(block){openModal('手記の資料',(block.images||[]).map(im=>`<figure class="evidence-view"><img src="${esc(im.src)}" alt="${esc(im.alt||'作中の図')}"><figcaption><p>${esc(im.alt||block.text)}</p></figcaption></figure>`).join('')+(block.notes||[]).map(note=>`<div class="case-detail"><p>${esc(note)}</p></div>`).join(''))}
function showSettings(){openModal('読書の設定',`<div class="setting"><label for="font-size">文字の大きさ <output id="font-output">${settings.font}px</output></label><input id="font-size" type="range" min="16" max="27" step="1" value="${settings.font}"></div><div class="setting"><label for="text-speed">文字の表示<select id="text-speed"><option value="0">一度に表示</option><option value="25">ゆっくり</option><option value="45">標準</option><option value="75">速く</option></select></label></div><div class="setting"><label for="auto-delay">自動送りの間隔 <output id="auto-output">${settings.auto}秒以上</output></label><input id="auto-delay" type="range" min="3" max="12" value="${settings.auto}"><p>文章の長さに応じて、読む時間を加えます。</p></div><div class="setting"><label>本文のみの表示色</label><div class="choice"><button id="paper-theme" class="${settings.theme==='paper'?'active':''}">紙の色</button><button id="night-theme" class="${settings.theme==='night'?'active':''}">夜の色</button></div></div><div class="setting"><label for="sound-setting">ページ送りの音<select id="sound-setting"><option value="false">鳴らさない</option><option value="true">小さく鳴らす</option></select></label></div><div class="setting"><hr><p>進み具合はこの端末に自動保存されます。別の端末へ移すときは記録を書き出してください。</p><div class="modal-actions"><button id="export-save">読書の記録を書き出す</button><button id="import-save">読書の記録を読み込む</button><button id="offline-save">全作品の本文を端末に保存</button></div><input class="file-input" id="save-file" type="file" accept="application/json,.json"><div id="offline-status" class="small" aria-live="polite"></div></div>`);
$('#text-speed').value=String(settings.speed);$('#sound-setting').value=String(settings.sound);$('#font-size').oninput=e=>{settings.font=Number(e.target.value);$('#font-output').textContent=settings.font+'px';applySettings();repaginate();persist()};$('#auto-delay').oninput=e=>{settings.auto=Number(e.target.value);$('#auto-output').textContent=settings.auto+'秒以上';persist()};$('#text-speed').onchange=e=>{settings.speed=Number(e.target.value);persist()};$('#sound-setting').onchange=e=>{settings.sound=e.target.value==='true';if(settings.sound)clickSound();persist()};for(const t of ['paper','night'])$('#'+t+'-theme').onclick=()=>{settings.theme=t;applySettings();persist();showSettings()};$('#export-save').onclick=exportSave;$('#import-save').onclick=()=>$('#save-file').click();$('#save-file').onchange=importSave;$('#offline-save').onclick=saveOffline;
$('.close').onclick=closeModal}
function exportSave(){record();const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ホームズ_読書の記録.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('読書の記録を書き出しました。')}
async function importSave(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error('large');const s=JSON.parse(await file.text());if(s.version!==VERSION||!s.progress||typeof s.progress!=='object'||!Array.isArray(s.seen))throw Error('shape');const clean={version:VERSION,progress:{},seen:s.seen.filter(x=>typeof x==='string'&&characters[x]),settings:cleanSettings(s.settings||settings)};for(const w of catalog.works){const p=s.progress[w.code];if(p&&Number.isInteger(p.index)&&p.index>=0)clean.progress[w.code]={index:Math.min(p.index,Math.max(0,w.blockCount-1)),page:Math.max(0,Math.min(10000,Number(p.page)||0)),offset:Number.isInteger(p.offset)?Math.max(0,Math.min(1000000,p.offset)):undefined,maxIndex:Math.min(Math.max(0,Number(p.maxIndex)||0),Math.max(0,w.blockCount-1)),complete:p.complete===true,history:cleanHistory(p.history,w.blockCount),updated:Date.now()}}if(catalog.works.some(w=>w.code===s.last))clean.last=s.last;save=clean;settings=clean.settings;applySettings();persist();home();toast('読書の記録を読み込みました。')}catch{toast('読書の記録を読み込めませんでした。書き出したJSONファイルを選んでください。')}}
async function saveOffline(){const button=$('#offline-save'),status=$('#offline-status');if(!('caches'in window)){toast('このブラウザでは端末への保存を利用できません。');return}button.disabled=true;const works=catalog.works.filter(ready);try{const store=await caches.open('holmes-content-5e689a2d3683936b');for(let i=0;i<works.length;i++){const url=`data/stories/${works[i].code}.json`;const r=await fetch(url).then(checkResponse);await store.put(new Request(new URL(url,location.href)),r);if(status.isConnected)status.textContent=`本文を保存しています ${i+1} / ${works.length}`;}if(status.isConnected)status.textContent=`${works.length}作品の本文を保存しました。画像は表示したものから順に保存されます。`;toast('本文の保存が終わりました。')}catch{if(status.isConnected)status.textContent='保存を中断しました。通信と端末の空き容量を確認して再度お試しください。'}finally{if(button.isConnected)button.disabled=false}}
function showAbout(){openModal('この事件簿について',`<div class="case-detail"><p>アーサー・コナン・ドイルによる長編4作品・短編56作品を、日本語で読む事件簿です。${catalog.releaseReady?'':'現在は制作中で、全文の収録は'+catalog.works.filter(ready).length+'作品です。'}本文の順序を保ち、作品同士を事件の推定時系列で並べています。</p><p>年が特定できない作品や、本文の年代に矛盾がある作品は推定として扱い、各作品の入口に根拠を記しています。</p><p>日本語本文は、提供された原文全集からこの版のために翻訳しました。地の文・会話・手紙・回想を収録しています。</p><p>原文：<a href="https://sherlock-holm.es/" target="_blank" rel="noopener">The Complete Sherlock Holmes</a> 第3.1版（2014年3月15日）。</p></div><p class="small">読書の記録は端末内に保存されます。画面・人物画・翻訳は本作品用の制作物です。</p><div class="modal-actions"><button id="coverage-report">収録情報を見る</button></div>`);$('#coverage-report').onclick=()=>openModal('収録情報',`<p class="small">収録作品：${catalog.works.filter(ready).length} / 60<br>翻訳済み段落等：${catalog.works.reduce((n,w)=>n+(w.translatedBlocks||0),0).toLocaleString()}<br>本文・手紙・見出し・図版の原文対応を保持しています。</p>`)}
function clickSound(){if(!settings.sound)return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(480,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(200,audioContext.currentTime+.025);g.gain.setValueAtTime(.018,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.035);o.connect(g);g.connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.04)}catch{}}
function wireActions(scope){const actions={home:()=>{record();home()},library:()=>showLibrary(),people:showPeople,settings:showSettings,about:showAbout,previous,history:showHistory,auto:toggleAuto,reading:()=>{settings.mode='reading';renderReading()},stage:()=>{settings.mode='stage';renderStage()}};scope.querySelectorAll('[data-action]').forEach(b=>{if(actions[b.dataset.action])b.onclick=actions[b.dataset.action]})}
document.addEventListener('keydown',e=>{if(!modal.hidden){if(e.key==='Escape')closeModal();if(e.key==='Tab'){const items=[...modal.querySelectorAll('button,input,select,a[href]')].filter(x=>!x.disabled&&x.offsetParent);if(items.length){const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault()}}}return}if(view==='reader'&&(settings.mode==='stage'||settings.mode==='reading')&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){if(e.key==='ArrowRight'||(e.key===' '&&document.activeElement.id!=='advance')){e.preventDefault();next()}else if(e.key==='ArrowLeft'){e.preventDefault();previous()}else if(e.key==='Escape')showSettings()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(autoTimer);record()}else scheduleAuto()});window.addEventListener('pagehide',record);let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(book&&(settings.mode==='stage'||settings.mode==='reading')&&modal.hidden){repaginate()}},120)});window.visualViewport?.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(book&&modal.hidden)repaginate()},120)});document.fonts?.addEventListener('loadingdone',()=>{if(book)repaginate()});
boot();
